### ISSUE TITLE
Entering personal details - other as title

### ISSUE THREAD

**Issue by Peter-Reavill** [findsorguk/findsorguk#1001]
Could you please set the database so when you select 'other' as a gender neutral title option in the drop down list of peoples titles it then doesn't display on the database.
![image](https://cloud.githubusercontent.com/assets/4980300/11093592/04cbf45c-8883-11e5-85e2-30f6222021c9.png)

see PAS database: 
https://finds.org.uk/database/people/person/id/29913 
and record:
https://finds.org.uk/database/artefacts/record/id/750970

**Comment by s-moon** [comment]
@Peter-Reavill This is now fixed. No more 'Other' in names. :+1:

**Comment by Peter-Reavill** [comment]
Thanks Stephen - much appreciated

Peter



Peter Reavill
Finds Liaison Officer – Shropshire and Herefordshire
Portable Antiquities Scheme
Tel: 01584 813 641
Web: http://finds.org.uk<http://finds.org.uk/>
Twitter: PAS in the Marches<https://twitter.com/PeterReavill> @PeterReavill<https://twitter.com/PeterReavill>
