### ISSUE TITLE
Detect Caps Lock Key on Login Form

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1018]
A user recently ran into some problems when entering her password where she didn't realise she had her caps lock key in use. Could a check be made on login to alert the user if this is the case?

Possibly something like [here](http://stackoverflow.com/questions/348792/how-do-you-tell-if-caps-lock-is-on-using-javascript) to detect it?

You can see an example of where Quora do something like this, below:

![quora](https://cloud.githubusercontent.com/assets/1986262/11978202/894696aa-a981-11e5-804d-4274207ed386.PNG)

**Comment by portableant** [comment]
Possible solution here http://jsfiddle.net/nosilleg/tBB58

**Comment by s-moon** [comment]
That looks good. There's a funny scenario when it doesn't work (but doesn't really matter). If you click directly into the password field, but type nothing, it doesn't detect the caps lock. Or rather, doesn't indicate it is on/off. Definitely looks usable though.

Have a good Xmas!
