### ISSUE TITLE
Staff contact information has confusing "staffregion" field

### ISSUE THREAD

**Issue by rjw57** [findsorguk/findsorguk#1019]
As a little experiment, I created a website which makes use of the JSON data at https://finds.org.uk/contacts/index/index/format/json to provide a location-search for FLOs. (https://rjw57.github.io/findmyflo) Initially this assigned a "region" to each FLO based on the "staffregion" field in the record. This region appears to bear no relation to the actual FLO's responsibilities. For example, the record for the, I assume, Gloucestershire FLO has the following fields (unreleated personal details redacted although there's a typo in the HTML for the real profile):

```json
{
			"id":"54",
			"firstname":"XXXX",
			"lastname":"XXXX",
			"email_one":"XXXX",
			"address_1":"Bristol City Museum, Queens Road, Bristol",
			"address_2":"Queens Road",
			"town":"Bristol",
			"county":"Gloucestershire",
			"postcode":"BS8 1RL",
			"telephone":"XXXX",
			"fax":null,
			"role":"7",
			"longitude":"-2.605306",
			"latitude":"51.456045",
			"created":"2003-04-22 00:00:01",
			"updated":"2010-04-08 09:18:39",
			"profile":"XXXX",
			"staffregions":"Somerset & Dorset",
			"staffroles":"Finds Liaison Officer"
}
```

The ``staffregions`` field is "Somerset & Devon".

It's not clear to me what the ``staffregions`` field actually means.

**Comment by portableant** [comment]
Now this is awesome. :+1: 
Staff regions is a bit of a mess. It refers to the areas that they historically covered when the Scheme first ran. Could be ignored?

**Comment by rjw57** [comment]
OK. Could be removed? Or is that non-trivial?

**Comment by portableant** [comment]
Easy to remove, not rendered in the view html or used elsewhere. I'll comment the code out in case anyone complains that they used it (I do not think that they do.) 10 mins and will be done.

**Comment by rjw57** [comment]
Super, thanks! :smile:
