### ISSUE TITLE
Broken link on https://finds.org.uk/about/contactus

### ISSUE THREAD

**Issue by rjw57** [findsorguk/findsorguk#1020]
At the bottom of the "[contact us](https://finds.org.uk/about/contactus)" page is the following:

> If your query is related to getting objects found within the boundaries of England and Wales recorded with the Scheme then go to our contacts page.

Where "contacts page" links to https://finds.org.uk/getinvolved/contacts. This is a 404. (Discovered when trying to get a list of FLOs for the project in #1019.)

**Comment by portableant** [comment]
I'll fix that.
