### ISSUE TITLE
York FLO has incorrect post code

### ISSUE THREAD

**Issue by rjw57** [findsorguk/findsorguk#1022]
The post code listed on https://finds.org.uk/contacts for the York FLO is "Y01 7FR" (note: Y, *zero* rather than Y, O). Should anyone be mad enough to use the post code with the Google Map rendering API, this will geo-locate to somewhere in deepest China requiring them to work around it :smile: .

**Comment by s-moon** [comment]
Fixed it on the contacts page. Thanks.

Love the FLO finder, by the way!
