### ISSUE TITLE
Clicking on System Environment generates an error

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1028]
As an Admin user, click on the red _Administer_ site button. Then click on _System Configuration_ on the list on the left. Here, click on _System Environment_:

![pas-system-environment](https://cloud.githubusercontent.com/assets/1986262/12475879/ca393d4a-c01d-11e5-9578-24615716bd6c.PNG)

This causes an exception as follows:

![pas-server-error-system-environment](https://cloud.githubusercontent.com/assets/1986262/12476165/7117bf8c-c01f-11e5-9cf3-83546bf5849c.PNG)

**Comment by portableant** [comment]
Cannot replicate on new OS
