### ISSUE TITLE
Hamburger menu button almost invisible when browser <980px

### ISSUE THREAD

**Issue by lesleyauk** [findsorguk/findsorguk#1034]
When the browser window is less than 980px wide, a breakpoint is hit that changes the main navbar to a dropdown which is activated by a "hamburger icon" button. However there is a style conflict between bootstrap and font-awesome that makes the hamburger icon invisible.

How it looks now: 
![findsorguk-invisible-hamburger](https://cloud.githubusercontent.com/assets/7544194/12648714/30420c10-c5d3-11e5-9ceb-e853a97b2ac1.png)

How it should look:
![findsorguk-fixed-hamburger](https://cloud.githubusercontent.com/assets/7544194/12648726/3749adb0-c5d3-11e5-90e6-d55d3e7f29bb.png)

**Comment by s-moon** [comment]
Tested locally and fixes the issue.
