### ISSUE TITLE
Add extra clarifying information on the What3Words link

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1043]
Currently, on a findspot, it looks like this:

![before](https://cloud.githubusercontent.com/assets/1986262/13529546/bbbb47c2-e214-11e5-81ba-371f951c9aa3.PNG)

This is to be changed to look like this when the user hovers their mouse over the text:

![after](https://cloud.githubusercontent.com/assets/1986262/13529548/bda50af0-e214-11e5-8879-4879b42ff64f.png)

**Comment by portableant** [comment]
This doesn't close the issue - that wording is needed on the unauthorised findspot partial too.

**Comment by s-moon** [comment]
OK, I'll look at that now.

**Comment by s-moon** [comment]
Thanks for that Dan. Change applied and released.
