### ISSUE TITLE
Some links on scheme not working

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1063]
At the following URL: https://finds.org.uk/datalabs/rss

The highlighted entries do not perform the expected functions, returning error pages when clicking on the rss link.

![rss-errors](https://cloud.githubusercontent.com/assets/1986262/17886118/4af9e1f2-6918-11e6-9dc2-0626f27eef78.PNG)

**Comment by portableant** [comment]
This just needed updating from the admin > content form. Closed and fixed by making edits.
