### ISSUE TITLE
0000-00-00 dates in finds rows

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#1078]
Dodgy dates of the form 0000-00-00 are finding their way into finds rows in the fields 'datefound1' and 'datefound2' when this should be NULL. This causes Solr import to fail in its current configuration. Data validation failing when any number other than properly formed date is entered.

**Comment by portableant** [comment]
@mchesterkadwell did you find the specific line that is causing this? Perhaps needs a custom date validator eg http://stackoverflow.com/questions/16767366/check-valid-date-in-zend-framework

**Comment by mchesterkadwell** [comment]
I think it's probably adding a validator here:
https://github.com/findsorguk/findsorguk/blob/master/app/forms/FindForm.php#L566
https://github.com/findsorguk/findsorguk/blob/master/app/forms/FindForm.php#L572
->addValidator('Date', true, (array('format' => 'yyyy-MM-dd')))
It's not perfect, but in a quick test it does seem to prevent dodgy months/days values and also the 0000-00-00 problem, at least.
