### ISSUE TITLE
Consider Making info@finds.org.uk Email Address an Image

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1114]
### Expected behaviour
Might be be better to use an image rather than a clickable link to reduce spam on the info@finds.org.uk email address of homepage.

### Actual behaviour
Currently using a clickable mailto style link on main page (http://www.finds.org.uk).

### Steps to reproduce the behaviour
See http://www.finds.org.uk at bottom of page, right side.

**Comment by portableant** [comment]
Not sure that this is good from an accessibility view point. How will screen readers pick this up?

**Comment by s-moon** [comment]
Could the alt text be written to be "the info at finds dot org dot uk email address" rather than "info@finds.org.uk"

Andrew T has said that they are getting loads of spam (which is what prompted all of this).

**Comment by portableant** [comment]
How about we go for a more elegant solution - re #1113. If we change contact us to a link that goes to the web contact form with a captcha. That may well solve the problem.

**Comment by s-moon** [comment]
Do they both end up at the same place? If so, that sounds much better :-)

**Comment by portableant** [comment]
Yes and they also get logged as queries to the database.

**Comment by s-moon** [comment]
OK, that's a plan then!

**Comment by portableant** [comment]
On https://github.com/findsorguk/findsorguk/blob/b2d4eaa7705f87c98a429b17e5f6f8473b672db0/app/modules/about/controllers/ContactusController.php#L38 the captcha is currently disabled, it will be really easy to reactivate this. Perhaps when server refresh done?
