### ISSUE TITLE
Quarantine items

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1165]
### Expected behaviour
Under the more like this section, only items appropriate to your view level should be returned.

### Actual behaviour
Public user sees quarantine records.

![screenshot_20180314-072005](https://user-images.githubusercontent.com/286552/37388473-99816020-2758-11e8-8de8-c656add4f810.jpg)

### Steps to reproduce the behaviour

Load https://finds.org.uk/database/artefacts/record/id/893349

**Comment by s-moon** [comment]
Resolved
