### ISSUE TITLE
Numismatics guides broken 

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1181]
### Expected behaviour
The numismatics guides should present data from wikipedia and elsewhere from linked data lookups using EasyRdf. This looks like:
<img width="982" alt="screen shot 2018-06-05 at 14 01 11" src="https://user-images.githubusercontent.com/286552/40977455-ef657326-68c8-11e8-873e-c14d04a5ab9d.png">

### Actual behaviour
The page breaks, see image below.
<img width="1204" alt="screen shot 2018-06-05 at 14 00 26" src="https://user-images.githubusercontent.com/286552/40977436-dcb3e65e-68c8-11e8-8732-42aea8ca429b.png">

### Steps to reproduce the behaviour
Load any coin guide emperor page for instance - eg https://finds.org.uk/romancoins/emperors/emperor/id/9

The fix for this is reasonably straight forward - amend 

`new EasyRdf_Graph`

And 

`EasyRdf_Namespace`

to be namespaced eg 

`new EasyRdf\Graph`

And

`EasyRdf\RdfNamespace::`

**Comment by s-moon** [comment]
Can you send me an email to the BM please Dan? Thanks
