### ISSUE TITLE
Google maps api error

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1196]
### Expected behaviour

The map div should load normally with all controls and multiple layers.

### Actual behaviour

The map renders with an error message as shown in image below and exceeded api limit in the console. 
![maps](https://user-images.githubusercontent.com/286552/44155450-3d95d6b2-a0a5-11e8-8a9f-6bedab320f50.jpg)

### Steps to reproduce the behaviour

Load any page with a map. Cancel window and the openstreetmap layer works only (as expected.)

**Comment by s-moon** [comment]
Issue resolved.
