### ISSUE TITLE
RDF load error for numismatic records

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1197]
### Expected behaviour

Page should load as expected with data pulled from Nomisma dynamically. 

### Actual behaviour

Page throws critical fatal error and fails to render as shown below.

![coins](https://user-images.githubusercontent.com/286552/44155665-d1c6bb80-a0a5-11e8-8bfa-3166a7c17042.jpg)

### Steps to reproduce the behaviour
Load any page that has an RIC or RRC number attached via Nomisma eg https://finds.org.uk/database/artefacts/record/id/912013

**Comment by s-moon** [comment]
Thanks for reporting this @portableant. It was already on the fix list but welcome anyway.

**Comment by portableant** [comment]
No worries, there are a bunch more failures within the coin guides. Eg https://finds.org.uk/romancoins/moneyers/called/by/6

**Comment by s-moon** [comment]
I haven't seen that one, thanks; creating a new issue for it now.
