### ISSUE TITLE
On review records displaying to wrong user groups

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1221]
### Expected behaviour

The More Like This function from Solr is meant to show finds in the correct access groups. Members of the public, recorders and those without rights should not be able to see on review or quarantine. 

### Actual behaviour

Records are displaying to public user from restricted groups. This could compromise data if the FLO has put in holding information. Screenshot below shows the leak in action:

![screenshot 2018-10-30 at 09 28 47](https://user-images.githubusercontent.com/286552/47708723-974bdf00-dc26-11e8-8ddc-47c2e27d0617.png)

Access to this should be restricted when calling solr by applying a filter to the range of ID numbers in workflow field of the schema and not in the post processing side: 
e.g.
      `$query->createFilterQuery('workflow')->setQuery('workflow:[3 TO 4]');`

### Steps to reproduce the behaviour

Do not login, load record https://finds.org.uk/database/artefacts/record/id/923895 for example.

**Comment by portableant** [comment]
You may know this. On your dev copy, there's a public method you can use to debug the query that gets sent through and print to browser. 
Either use ->debugQuery() or ->debugProcessing() and you might see where the problem lies. 
Are you still on solr 4.2? I don't know if this library without upgrade works with different versions as I never tested it on that environment. I have solr 7 on my dev machines now.

**Comment by s-moon** [comment]
Thanks for the tip. Resolved
