### ISSUE TITLE
Revise Treasure module structure

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#125]
**Current**

![currenttreasure](https://cloud.githubusercontent.com/assets/5013576/3398459/045da86a-fd30-11e3-8b45-e34ae3da4fe5.PNG)

**Proposed**

_What it looks like on visiting introduction page_

![proposedtreasure](https://cloud.githubusercontent.com/assets/5013576/3398468/1c0e6bb6-fd30-11e3-938a-24e29d3cf5d9.PNG)

_Each folder opened in turn to reveal subpages_

![whatistreasure](https://cloud.githubusercontent.com/assets/5013576/3398471/2fdd91b2-fd30-11e3-8f18-27956db2c52d.PNG)
![thetreasureprocess](https://cloud.githubusercontent.com/assets/5013576/3398475/328e395c-fd30-11e3-8826-fac73c44d009.PNG)
![treasurevaluation](https://cloud.githubusercontent.com/assets/5013576/3398476/329abb8c-fd30-11e3-9a96-634dc9a1dc47.PNG)
![treasureacquisition](https://cloud.githubusercontent.com/assets/5013576/3398477/329d0f9a-fd30-11e3-8a54-99868bc6417d.PNG)
![buyingandexporting](https://cloud.githubusercontent.com/assets/5013576/3398474/327e6d60-fd30-11e3-98f9-cc5e73d3155d.PNG)

**Comment by portableant** [comment]
This is now done.

**Comment by irichardson77** [comment]
Great!  Looking forward to it! 

Thank you,
Ian
