### ISSUE TITLE
Redirect to the ruler information page

### ISSUE THREAD

**Issue by Minakshi-Chidrawar** [findsorguk/findsorguk#1284]
### Expected behaviour
Ruler information page should be loaded.

### Actual behaviour
Throws an error as Not Found: 404.
![image](https://user-images.githubusercontent.com/22420871/62303390-f075c700-b473-11e9-9608-b847c6e989b5.png)

### Steps to reproduce the behaviour
https://training.finds.org.uk/admin/numismatics/rulertodenomination/rulerid/309/period/29

**Comment by s-moon** [comment]
Resolved
