### ISSUE TITLE
Why does PDF (and HERO) export disappear for a linked member, when drilling down in search?

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#1300]
Search for lots of records.
See PDF and HERO disabled.
Reduce recordset.
Button disappears.

**Comment by portableant** [comment]
Because system memory can't cope with more than 10-12k records. You'll get a white screen of death if you to further.

**Comment by s-moon** [comment]
It's the button disappearing that is odd - we're aware of the download limits. Instead of just being disabled, it just vanishes.

**Comment by s-moon** [comment]
Button now only visible for FA, Admin, FLO
