### ISSUE TITLE
Hamburger menu not expanding

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1318]
### Expected behaviour

Menu expands on click, whether logged in or out of the system

### Actual behaviour

Menu expansion fails to fire 

### Steps to reproduce the behaviour

On mobile device, login to the database and then try to fire the menu hamburger. Reproducible in chrome for desktop by using the mobile emulator.

**Comment by s-moon** [comment]
Can confirm that it *does not* work when logged in to database. 

When _not_ logged in, works in a variety of virtual and at least one physical mobile device.

No console errors visible.

**Comment by portableant** [comment]
Sorry, perhaps should have made clearer, only on the logged in side. I think it *could* be the session expiry javascript that is causing a conflict.
