### ISSUE TITLE
404 on jquery plugin

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1330]
### Expected behaviour

Jquery capslock plugin (jquery.jccapsalert.js) should fire on this page https://finds.org.uk/users/  alerting user  if caps lock is on.
 
### Actual behaviour

Page throws error:
GET https://finds.org.uk/users/js/jquery.jccapsalert.js net::ERR_ABORTED 404 (Not Found)
(index):269 Uncaught TypeError: jQuery(...).CapsLockAlert is not a function
    at HTMLDocument.<anonymous> ((index):269)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
(anonymous) @ (index):269
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2

Path https://finds.org.uk/users/js/jquery.jccapsalert.js should be https://finds.org.uk/js/jquery.jccapsalert.js

### Steps to reproduce the behaviour

Load the users login page.

**Comment by s-moon** [comment]
Thanks Dan. We'll take a look at it soon.
