### ISSUE TITLE
Remove or redirect day of archaeology panel

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#1351]
On the homepage of finds.org.uk is a card for the day of archaeology project I ran with various collaborators. This has since been archived to the Archaeological Data Service at https://archaeologydataservice.ac.uk/archives/view/dayofarch_nearch_2018/index.cfm Could the panel be either removed or redirected please?
Dan

**Comment by s-moon** [comment]
No problem Dan. On the next release we do we'll update this - shouldn't be that far away.

**Comment by portableant** [comment]
Thanks! BTW, your new cookie banner text flows over on mobile...

**Comment by s-moon** [comment]
Resolved - panel removed.
