### ISSUE TITLE
Jetton/token data form

### ISSUE THREAD

**Issue by rwebley** [findsorguk/findsorguk#208]
Could I request the addition of an extra box in which initial marks can be recorded, please?  After the fashion of such freetext boxes, on the early-medieval/medieval/post-medieval coin data forms this would sit below Reverse inscription and above Die Axis measurement.

Many thanks,

Rob

**Comment by portableant** [comment]
What is the reasoning for doing so? Just so we document it.

**Comment by portableant** [comment]
No update in 12 days. Closing for now.
