### ISSUE TITLE
Image uploading issues

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#334]
Metadata adding – the workflow for adding metadata to multiple images – after adding metadata to the first image that needs it, it is tricky to get back to the next one that needs doing. Is it possible to redirect back to the ‘Images attached to this record’ page after editing? I can see it’s using the existing image edit function, which redirects to the ‘Large image view and metadata’ page after editing, so not a straight forward fix.

On the ‘Images attached to this record’ page, the following don’t seem to update even if you have entered metadata:
Broad period: Period needs to be entered.
Key words: Key words need entering

Also if there's no metadata, the pics don't seem to turn up in My Images/All Images, which is otherwise a nice way to keep track of things.

**Comment by portableant** [comment]
These two are done - Broad period: Period needs to be entered. Key words: Key words need entering
See commit 828fefdc80f9d1fc4a7580eaebaa3264a5f0a6a2
