### ISSUE TITLE
Findspot helper not found

### ISSUE THREAD

**Issue by portableant** [findsorguk/findsorguk#341]
Plugin by name 'FindSpot' was not found in the registry; used paths: Database_View_Helper_: /var/www/finds.org.uk/app/modules/database/views/helpers/ EasyBib_View_Helper_: EasyBib/View/Helper/ ZendX_JQuery_View_Helper_: ZendX/JQuery/View/Helper/ Pas_View_Helper_: Pas/View/Helper/ Zend_View_Helper_: Zend/View/Helper/:/var/www/finds.org.uk/app/views/helpers/

**Comment by mchesterkadwell** [comment]
Not sure this is resolved quite yet...

PHP Catchable fatal error:  Method Pas_View_Helper_FindSpot::__toString() must return a string value in /var/www/finds.org.uk/app/modules/database/views/scripts/hoards/record.phtml on line 147

PHP Catchable fatal error:  Method Pas_View_Helper_FindSpot::__toString() must return a string value in /var/www/finds.org.uk/app/modules/database/views/scripts/artefacts/record.phtml on line 204
