### ISSUE TITLE
Button font size too small?

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#347]
Personal opinion, but, I think the button font size is now too small, especially where contrast between white text and background colour is lower. 

Cf. 13pt for old style buttons

![new-comb](https://cloud.githubusercontent.com/assets/5013576/5918198/f90af2dc-a61d-11e4-86dd-36ec6433ab8e.JPG)

New 11pt style

![edit-findb](https://cloud.githubusercontent.com/assets/5013576/5918222/02c612de-a61e-11e4-9a52-188e3b4727ea.JPG)

**Comment by mchesterkadwell** [comment]
Difference is between 'btn-small btn-primary' and just 'btn-primary'

**Comment by portableant** [comment]
Can over ride this in custom-bootstrap css using .btn-small { font-size:13px;}

**Comment by mchesterkadwell** [comment]
Is this what we want to do? There doesn't seem to be any other difference between the two. I thought you might have restyled them all for a reason.

**Comment by portableant** [comment]
Leave as is, ask FLOS for opinion?
