### ISSUE TITLE
Improve error messages for non-existent records

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#350]
For non-existent artefact records you get this:

Pas_Controller_Action_Helper_AvailableOrNot->checkAccess(Array)
The data sent to this helper must be an array

For non-existent hoards records you get this:

Pas_Controller_Action_Helper_AvailableOrNot->checkAccess(Array)
The workflow key is missing from this record

**Comment by portableant** [comment]
Yes, these are going to change when I make error pages more friendly.
