### ISSUE TITLE
Image label guidance missing

### ISSUE THREAD

**Issue by hgeake** [findsorguk/findsorguk#555]
We used to have some image label guidance at the foot of the image metadata add/edit screen. Here is a partial screenshot:
![image labels old screen](https://cloud.githubusercontent.com/assets/1135437/5999943/912f7fdc-aacf-11e4-9dfa-bf7c62c3388f.jpg)

See right at the bottom for a bit of what we used to have. If this could be revived it would be very helpful.

**Comment by portableant** [comment]
Oh that, yes of course.
