### ISSUE TITLE
Landowner not appearing on record view

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#567]
Anna Tyacke reports that landowner does not appear on the record view of an artefact for her as FLO. It should be under the heading 'Land owned by'.

**Comment by atyacke** [comment]
Should be land owned by ...
And the landowner is still in the field when I edit the findspot, but I added him very recently so perhaps he has fallen into a chasm!
Thanks, Anna

**Comment by mchesterkadwell** [comment]
It's not just you, I can see the problem.

**Comment by atyacke** [comment]
Oh phew thanks.

**Comment by portableant** [comment]
This will be fixed by Friday.
