### ISSUE TITLE
Make page titles and sidebar links consistent sitewide

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#61]
Inconsistent text between the sidebar link users click on and the title of the page they get back can be a source of confusion for users. e.g. (this is not the worst example)
![screen shot 2014-05-03 at 09 22 27](https://cloud.githubusercontent.com/assets/5013576/2869938/20a4221a-d29c-11e3-84e4-11c346e9fb27.png)

**Comment by portableant** [comment]
Think this is now done in revamp too.
