### ISSUE TITLE
FLO unable to edit numismatic section on PUBLIC record

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#631]
No buttons. Reported by Kurt Adams.

**Comment by portableant** [comment]
@mchesterkadwell  can you replicate this?

**Comment by mchesterkadwell** [comment]
This has been re-reported by Amy Downes with better information, e.g. PUBLIC-353CBA

![image](https://cloud.githubusercontent.com/assets/5013576/6145268/f08b88e0-b1d7-11e4-96cd-5b583873d5ba.png)
