### ISSUE TITLE
Images created by PUBLIC recorders not visible

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#632]
Reported by Kurt Adams. Example: PUBLIC-E360A1 Thumbnail on search results showing but no image and gives error on record view:
That image (filename: Cabpture.PNG) is unavailable.

**Comment by portableant** [comment]
Png files aren't valid for digital preservation. I'll look on the server and see if they exist. Not a code bug.

**Comment by mchesterkadwell** [comment]
But isn't the uploader supposed to prevent upload of PNG?

**Comment by portableant** [comment]
Created on: Tuesday 4th December 2012 so prior to that date, any image format would get parsed.

**Comment by mchesterkadwell** [comment]
But existing invalid formats should still be visible... or not?

**Comment by portableant** [comment]
If they exist on the server. I think some of these images may have been lost when we had server crash in 2013.

**Comment by portableant** [comment]
Closing as this is not a code error. From email archive, I contacted finder and asked for him to send me these images and I had no reply.
