### ISSUE TITLE
Images uploaded by user not visible to user

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#636]
Anna Tyacke reports she cannot see images on her own records.

**Comment by portableant** [comment]
Cannot replicate this.

**Comment by mchesterkadwell** [comment]
I've already asked her twice for more information.

**Comment by atyacke** [comment]
I can see images on the record but when I try and view there is blank page - I sent a screen shot of this. So then I cannot download the images either which have been trying to do for Michael.

Also editing record CORN-24084B and I keep putting spaces back in in the text of the description field / box but it takes them out again - three times now - when save the record. Will send screen shot of this via email.

**Comment by portableant** [comment]
Anna

Can you file one problem per issue please? You don't say which record you cannot see images on.

I just emailed asking for this to happen to everyone. These are not related problems. 
Are you pasting from Word? As the contents of your record's text looks like it. It is generating invalid html so it will render text as squished. eg

`<p>Cast copper alloy apothecary weight,<span>square in plan and rectangular in section. Both faces have the symbol </span>Э&yuml;<span>in relief within a square border. This is the mark of value for 2 scruples, which should weigh and the weight weighs 2.6g, so it comes under the standard weight. These weightswere used by physicians and apothecaries to measure the ingredients for medical recipes.</span></p>`


Dan

**Comment by atyacke** [comment]
See previous email.
No not pasting from anywhere - just typing in - apart from symbol but problem was happening before that.
I said to Mary that having problem with images in all records - I have tried to download images from quite a few - as I needed some last week, over the weekend and today for Michael of the hoards that he is writing about for AR. I have the original images at work so told Mary as she said it couldnt be dealt with before this week that I can get them tomorrow when I am at work.
Thanks,
Anna
Anna Tyacke MA Cantab MA Leics AMA
Finds Liaison Officer for Cornwall
Portable Antiquities Scheme
www.finds.org.uk
Royal Cornwall Museum
River Street
Truro
TR1 2SJ
01872 272205 ext 219
----Original message----
From : notifications@github.com
Date : 09/02/2015 - 17:03 (GMTST)
To : findsorguk@noreply.github.com
Cc : annatyacke@btinternet.com
Subject : Re: [findsorguk] Images uploaded by user not visible to user (#636)
Anna
Can you file one problem per issue please? You don't say which record you cannot see images on.
I just emailed asking for this to happen to everyone. These are not related problems. 
Are you pasting from Word? As the contents of your record's text looks like it. It is generating invalid html so it will render text as squished. eg
<p>Cast copper alloy apothecary weight,<span>square in plan and rectangular in section. Both faces have the symbol </span>Э&yuml;<span>in relief within a square border. This is the mark of value for 2 scruples, which should weigh and the weight weighs 2.6g, so it comes under the standard weight. These weightswere used by physicians and apothecaries to measure the ingredients for medical recipes.</span></p>
Dan

**Comment by atyacke** [comment]
Fixed cheers!

Sent from my Sony Xperia™ smartphone

---- Daniel Pett wrote ----
