### ISSUE TITLE
Revise general site structure

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#66]
@portableant I realise there are probably good historical and practical reasons why we can't do all of this, but here is my suggestion anyway. I've left architecture for another discussion. I'm slightly nervous about suggesting big changes that cost us a lot of dev time without having proper user journeys to guide us.

I'd also like to reword some of the item titles/labels and maybe question if some pages could be removed altogether, but that's for another time. Need to think more about where to put Help documentation.

![screen shot 2014-05-06 at 18 09 56](https://cloud.githubusercontent.com/assets/5013576/2892811/754ab5b6-d541-11e3-82a9-a471c6e4698d.png)
![screen shot 2014-05-06 at 18 10 07](https://cloud.githubusercontent.com/assets/5013576/2892888/62c61df8-d542-11e3-9b47-6d005781ac96.png)

**Comment by portableant** [comment]
All done for now, the vocab one is still to be addressed.
