### ISSUE TITLE
Missing thumbnail KENT-07C1ED

### ISSUE THREAD

**Issue by Ucljo** [findsorguk/findsorguk#692]
This records preview image seems to have an issue up until the database update from its creation the preview image is failing to show in database search. on Wednesday 3 Feb after the database update the preview image was showing up by the 4th however the image was once again missing.

I've tried forcing an index update and indeed replacing the image entirely, nothing seems to work.

Any ideas?

**Comment by portableant** [comment]
On the case, there's a fault in the query that is not finding the image on update.

**Comment by portableant** [comment]
Resolved. Image thumbnail shows.
