### ISSUE TITLE
Changing workflow for hoards gives Solr updater error

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#750]
Notice: Undefined offset: 0 in /var/www/finds.org.uk/library/Pas/Controller/Action/Helper/SolrUpdater.php on line 253

Catchable fatal error: Argument 1 passed to Pas_Controller_Action_Helper_SolrUpdater::cleanData() must be an array, null given, called in /var/www/finds.org.uk/library/Pas/Controller/Action/Helper/SolrUpdater.php on line 253 and defined in /var/www/finds.org.uk/library/Pas/Controller/Action/Helper/SolrUpdater.php on line 265

**Comment by portableant** [comment]
That suggests that the hoard query is empty...
