### ISSUE TITLE
Iron Age coin menus not populating

### ISSUE THREAD

**Issue by adamdaubney** [findsorguk/findsorguk#784]
The only option allowed for ANY of the iron age denominations is the Trinovantes.

**Comment by portableant** [comment]
When, what url are you hitting? I cannot replicate this.

**Comment by Peter-Reavill** [comment]
Hi Dan - I'm getting the same issue here 
![image](https://cloud.githubusercontent.com/assets/4980300/6394658/d2332642-bdca-11e4-841c-99ea6dc778f3.png)

https://finds.org.uk/database/coins/add/broadperiod/IRON+AGE/findID/PAS54EF377F00102C/returnID/707559

**Comment by Peter-Reavill** [comment]
Oh - interesting - came out by saving and then went back in and all the menus have populated?

**Comment by portableant** [comment]
Ah now that helps more!
