### ISSUE TITLE
Missing fields in viewable record

### ISSUE THREAD

**Issue by irichardson77** [findsorguk/findsorguk#931]
There are several fields in the database record for which data can be input, but which do not display on the viewable record, even for 'FA' users.

These include:
Discovery Circumstances
Discovery Method
Museum accession number
Current Location

It would be helpful if they could be displayed. 
Thank you,
Ian

**Comment by portableant** [comment]
Closed in 5997cd13cdc524dc4e6f5c0e00bb506816d2878d
