### ISSUE TITLE
Image error message when adding new image

### ISSUE THREAD

**Issue by adamdaubney** [findsorguk/findsorguk#954]
Several of us are getting the following error message when adding NEW images to a record (i.e. the image HASN'T already been uploaded to the database

![error1](https://cloud.githubusercontent.com/assets/5380631/10070379/fb6c500e-62a9-11e5-8153-5152357ca94d.jpg)

**Comment by adamdaubney** [comment]
Update: the image attaches in spite of this error message, but does not show in the grid-form thumbnail (i.e. it does show when the record is opened).

**Comment by portableant** [comment]
I think that this will get resolved with the new Imagick code deployed in latest build. Closing for now.
