### ISSUE TITLE
Error Message when saving edited record.

### ISSUE THREAD

**Issue by ABolton** [findsorguk/findsorguk#956]
Many, if not all of us are getting an Error 500 message when saving an edited record.

Internal Server Error: 500
Search engine error: The server is not responding, but will be back shortly 

Is the text with lego Indy Jones

**Comment by KatieHinds** [comment]
Me too.

**Comment by portableant** [comment]
The solr index was locked, I'm around and getting plagued by emails, so I fixed it. This closes #956 and closes #955
