### ISSUE TITLE
Unable to save new records to training database - Internal Server Error: 500 

### ISSUE THREAD

**Issue by pastexplorersoutreach** [findsorguk/findsorguk#972]
When trying to create a 'skeleton' record (object type, broad period, period from, period to) on the PAS training database (https://training.finds.org.uk/database/) and clicking to save record, this error message appears:

![error](https://cloud.githubusercontent.com/assets/13995544/10279131/e2e84a4c-6b5a-11e5-9e51-fdbe5ec0c8c0.jpg)

**Comment by portableant** [comment]
Try now. Tomcat7 restarted.
