### ISSUE TITLE
Copyright change on West Midlands Images

### ISSUE THREAD

**Issue by ABolton** [findsorguk/findsorguk#983]
Hi there,

for the copyright of images, for institutions HESH, WAW, and WMID would you mind changing it from Birmingham Museum and Art Gallery or Birmingham City Council to Birmingham Museums Trust please?

Thanks

Angie

**Comment by s-moon** [comment]
Hi Angie,

This should now be changed for both (*Birmingham Museum & Art Gallery*, and *Birmingham City Council*).

Thanks, Steve

**Comment by portableant** [comment]
Just thought about this, @ABolton you don't want all the old images updated to reflect the change do you. If you do, then the update query for @s-moon's reference (sorry forgot about this and it is bad db design as the field is not normalised) is:

    UPDATE `slides` 
    SET imagerights = 'Birmingham Museums Trust'
    WHERE `imagerights` LIKE 'Birming%'

**Comment by portableant** [comment]
I'm closing this as we have had no comeback from @ABolton since.

**Comment by ABolton** [comment]
Dear Dan,



I hope I'm finding you well. I'm sorry, I've got behind with my emails. Yes, we'd like all the images from WAW-, WMID- and HESH to be Birmingham Museum Trust for the rights, and that also applies to the old images as well please.



Best wishes



Angie



Angie Bolton: Senior Finds Liaison Officer - Portable Antiquities Scheme
email: abolton@worcestershire.gov.uk<mailto:abolton@worcestershire.gov.uk>

telephone: 01905 25371

mobile number: 07766923958

address: Worcester Museum and Art Gallery, Foregate St., Worcester WR1 1DT
website: www.finds.org.uk<http://www.finds.org.uk/>



Please be aware I do not work on Tuesdays or Wednesdays.

________________________________

**Comment by ABolton** [comment]
Hi there,



I've just got to this email. I've replied, belatedly, hanf an hour ago. I'm sorry for the delayed response.



Angie



Angie Bolton: Senior Finds Liaison Officer - Portable Antiquities Scheme
email: abolton@worcestershire.gov.uk<mailto:abolton@worcestershire.gov.uk>

telephone: 01905 25371

mobile number: 07766923958

address: Worcester Museum and Art Gallery, Foregate St., Worcester WR1 1DT
website: www.finds.org.uk<http://www.finds.org.uk/>



Please be aware I do not work on Tuesdays or Wednesdays.

________________________________
