### ISSUE TITLE
Profile Editing - Server Error 500

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#986]
On user account screen (https://finds.org.uk/users/account), clicking on either *Edit staff profile* or *Staff profile image*:

![edit-options](https://cloud.githubusercontent.com/assets/1986262/10638845/f09c8f16-7804-11e5-8071-fa353ff9d80c.PNG)

results in the following error:

![error-500](https://cloud.githubusercontent.com/assets/1986262/10638863/03f18c38-7805-11e5-85b2-3b16197498a2.PNG)

**Comment by portableant** [comment]
Okay, the first link - edit staff profile throws the wrong exception at the moment. YOu get this because you do not have a profile under staff. The option should not be available really. Second one will be fixed with next commit.
