### ISSUE TITLE
Enhancement: Focus on Login Screen

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#988]
When logging in:

![login](https://cloud.githubusercontent.com/assets/1986262/10676614/59ec54ba-78ff-11e5-9e39-83faa897445e.JPG)

it would be nice to have the focus move to the username field ready for typing.

![username](https://cloud.githubusercontent.com/assets/1986262/10676621/60848ce8-78ff-11e5-93dc-c4edcd86affa.JPG)

This will make it especially useful for mobile users.

**Comment by portableant** [comment]
You can do this via various means, however, do check about web accessibility and auto focus on forms eg: http://stackoverflow.com/questions/2180645/is-automatically-assigning-focus-bad-for-accessibility

**Comment by s-moon** [comment]
Resolved. Thanks for the pointers.
