### ISSUE TITLE
Input Form for Copyrights

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#989]
A facility to be able to edit copyright messages within the web application (which are attached to future images) would be a useful addition.

**Comment by portableant** [comment]
Sure, go for it. To do this:

* Create controller in admin module - CopyrightsController.php
* Create CRUD actions within controller
* Create folder admin/views/scripts/copyrights
* Create .phtml file for each action
* Create form in app/forms

A good example to follow would be admin/acronyms. Have a go and let me know how you get on? @mchesterkadwell just so you know @s-moon is starting off developing on the codebase :clap:

**Comment by portableant** [comment]
This was closed in d363e04d1ee1eab4701afdefe911f29e5c715eee
