### ISSUE TITLE
Ensuring all names use title case

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#996]
When registering, the input forms are quite permissive about capitalisation so for example, someone might write that their name is "stephen moon", rather than "Stephen Moon".

This correct capitalisation could be automatic, making the process seemless. In addition, all existing records could have the same amendment made, to bring them to the same standard as the input form.

Should any entries be incorrectly changed, the user should still be able to edit their form and correct it.

**Comment by portableant** [comment]
Here's a skeleton:

< ?php
 /**
 * Convert a string to titlecase.
 */
class stringToTitle implements Zend_Filter_Interface
{
    /**
     * Encoding for the input string
     * @var string
     */
    protected $_encoding = null;
 
    /**
     * Set the input encoding for the given string
     *
     * @param  string $encoding
     * @throws Zend_Filter_Exception
     */
    public function setEncoding($encoding = null)
    {
        if (!function_exists('mb_convert_case')) {
            require_once 'Zend/Filter/Exception.php';
            throw new Zend_Filter_Exception('mbstring is required for this feature');
        }
        $this->_encoding = $encoding;
    }
 
    /**
     * Defined by Zend_Filter_Interface
     *
     * Returns the string $value, converting characters to titlecase as necessary
     *
     * @param  string $value
     * @return string
     */
    public function filter($value)
    {
        if ($this->_encoding) {
            return mb_convert_case((string) $value, MB_CASE_TITLE, $this->_encoding);
        }
        return ucwords((string) $value);
    }
}

**Comment by mchesterkadwell** [comment]
Not all surnames are entirely capitalised. For example ones with a non-English origin 'von Trappe', 'van Dam', 'de Wit'.

**Comment by s-moon** [comment]
Hi Mary!

Yes, agreed, but the vast majority should be fine and for the cases like you mention, they could edit their record and fix it manually (i.e. it wouldn't be enforced on the edit page).

I think it would improve a lot of the data that goes in because there are quite a few people that don't use capitals. However, at the end of the day, I realise that it is all cosmetic ;-)

Thanks, Steve

**Comment by mchesterkadwell** [comment]
Hi Steve! Just thinking through the details of what this might mean... Does that filter also decapitalise letters in the middle of surnames? For example, would McDonald be affected? I can see that the edit form is useful for undoing but I'm not sure that users will necessarily realise they can use that to fix their names. I tend to feel that users are more qualified than we are to know what the proper capitalisation of their names should be - except of course for the ones we're trying to catch... 

Would it be possible to add in a check to use the filter only if all the letters are lowercase (or all caps)? Alternatively ask them on submit "did you mean?" so they have the choice (I realise this second one is not straightforward)?

**Comment by s-moon** [comment]
That's a good point about McDonald and the way I would have done it would gave changed: McDonald o Mcdonald.

I like your idea of only applying it if everything is in caps or lowercase. That sounds like a good half-way step to catch the ones where *no* attempt has been made, but leave those people that have tried to capitalise.

The other suggestion would be brilliant but would require *a lot* more work, I would guess ;-)

**Comment by portableant** [comment]
Closing this for now, as work required is quite high.
