### ISSUE TITLE
Inconsistent formatting on institution statistics?

### ISSUE THREAD

**Issue by s-moon** [findsorguk/findsorguk#998]
On the following page:

https://finds.org.uk/database/statistics/institution

There appears to be some inconsistent formatting.

![unusualformattingoninstitutionstats](https://cloud.githubusercontent.com/assets/1986262/11036745/36896bd8-86f2-11e5-884d-9d97217ec50f.PNG)

**Comment by portableant** [comment]
The size change here is due to acronym styling being applied. See bootstrap.min.css:
    abbr {
    font-size: 90%;
    text-transform: uppercase;
    border-bottom: 1px dotted #ddd;
    cursor: help;
    }

**Comment by s-moon** [comment]
I did see that in the source but do you notice that it is also being applied to Cambridgeshire? That's what made me think something might be amiss. Note, this is in IE version 11.

![cam](https://cloud.githubusercontent.com/assets/1986262/11037061/c6d2a3ac-86f3-11e5-876d-e1b7489444ad.PNG)

But, this is interesting. In Chrome, we don't have any such visual issues:

![all-counties](https://cloud.githubusercontent.com/assets/1986262/11037066/d508ca3c-86f3-11e5-8027-bdbc3abbf23f.PNG)

Nor in Firefox:

![firefox-counties](https://cloud.githubusercontent.com/assets/1986262/11037121/10f8e19e-86f4-11e5-815b-a04323db535f.PNG)
